# Generated by Django 2.1.5 on 2020-04-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtRecordKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_record_keepers', to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStationRecordKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_station_record_keepers', to='location.PoliceStation')),
                ('sub_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_station_record_keepers', to='location.SubDivision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_station_record_keepers', to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='SSPRecordKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssp_record_keepers', to='account.User')),
            ],
        ),
    ]
