# Generated by Django 2.1.5 on 2020-04-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200419_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtrecordkeeper',
            options={'verbose_name': 'Court Record Keeper', 'verbose_name_plural': 'Court Record Keepers'},
        ),
        migrations.AlterModelOptions(
            name='policestationrecordkeeper',
            options={'verbose_name': 'Police Station Record Keeper', 'verbose_name_plural': 'Police Station Record Keepers'},
        ),
        migrations.AlterModelOptions(
            name='ssprecordkeeper',
            options={'verbose_name': 'SSP Record Keeper', 'verbose_name_plural': 'SSP Record Keepers'},
        ),
    ]
