# Generated by Django 3.0.7 on 2020-06-10 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20200419_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSPRecordKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsp_record_keepers', to='location.SubDivision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsp_record_keepers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DSP Record Keeper',
                'verbose_name_plural': 'DSP Record Keepers',
            },
        ),
    ]
