# Generated by Django 3.0.7 on 2020-06-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('account', '0005_dsprecordkeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtrecordkeeper',
            name='police_station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='court_record_keepers', to='location.PoliceStation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courtrecordkeeper',
            name='sub_division',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='court_record_keepers', to='location.SubDivision'),
            preserve_default=False,
        ),
    ]
