# Generated by Django 3.0.7 on 2020-06-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_no', models.CharField(max_length=50)),
                ('is_closed', models.BooleanField(default=False)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fir_list', to='location.PoliceStation')),
                ('sub_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fir_list', to='location.SubDivision')),
            ],
        ),
        migrations.CreateModel(
            name='FIRPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_index', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('date_registered', models.DateField()),
                ('date_created_on_system', models.DateField(auto_now_add=True)),
                ('under_section', models.CharField(max_length=100)),
                ('io_name', models.CharField(max_length=100)),
                ('accused_name', models.TextField(blank=True, null=True)),
                ('accused_status', models.TextField(blank=True, null=True)),
                ('limitation_period', models.PositiveIntegerField()),
                ('current_status', models.CharField(choices=[('Under Investigation', 'Under Investigation'), ('Challan Filed', 'Challan Filed'), ('Untraced', 'Untraced'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('current_status_date', models.DateField()),
                ('vrk_receival_date', models.DateField(blank=True, null=True)),
                ('vrk_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=50, null=True)),
                ('vrk_status_date', models.DateField(blank=True, null=True)),
                ('received_from_vrk_date', models.DateField(blank=True, null=True)),
                ('put_in_court_date', models.DateField(blank=True, null=True)),
                ('nc_receival_date', models.DateField(blank=True, null=True)),
                ('nc_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Reinvestigation', 'Reinvestigation')], max_length=50, null=True)),
                ('nc_status_date', models.DateField(blank=True, null=True)),
                ('received_from_nc_date', models.DateField(blank=True, null=True)),
                ('appointed_io', models.CharField(blank=True, max_length=100, null=True)),
                ('appointed_io_date', models.DateField(blank=True, null=True)),
                ('fir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='firBeta.FIR')),
            ],
        ),
    ]
