# Generated by Django 3.0.7 on 2020-06-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firBeta', '0002_auto_20200624_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firphase',
            name='current_status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
