# Generated by Django 3.0.7 on 2020-06-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firBeta', '0004_auto_20200628_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fir',
            options={'ordering': ['sub_division', 'police_station', '-pk'], 'verbose_name': 'FIR', 'verbose_name_plural': 'FIRs'},
        ),
    ]
