# Generated by Django 3.0.7 on 2020-06-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firBeta', '0005_auto_20200628_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='firphase',
            name='vrk_sent_back_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
