# Generated by Django 3.0.7 on 2020-07-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firBeta', '0006_firphase_vrk_sent_back_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='firphase',
            name='nc_sent_back_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
