# Generated by Django 3.0.7 on 2020-07-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firBeta', '0007_firphase_nc_sent_back_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastMailDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
