# Generated by Django 2.1.5 on 2020-04-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_no', models.CharField(max_length=50)),
                ('phase', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('date_created', models.DateField(auto_now=True)),
                ('io_name', models.CharField(max_length=50)),
                ('accused_name', models.TextField()),
                ('accused_status', models.CharField(choices=[('arrested', 'Arrested'), ('not_arrested', 'Not Arrested'), ('po', 'PO')], max_length=50)),
                ('limitation_period', models.PositiveIntegerField()),
                ('current_status', models.CharField(choices=[('under_invertigation', 'Under Invertigation'), ('challan_filed', 'Challan Filed'), ('untraced', 'Untraced'), ('cancelled', 'Cancelled')], max_length=50)),
                ('put_in_court', models.BooleanField(default=False)),
                ('put_in_court_date', models.DateField()),
                ('received_in_court', models.BooleanField(default=False)),
                ('received_in_court_date', models.DateField()),
                ('court_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('reinvestigation', 'Reinvestigation')], max_length=50)),
                ('reverted_by_court_date', models.DateField()),
                ('received_from_court_date', models.DateField()),
                ('appointed_io', models.CharField(max_length=50)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firs', to='location.PoliceStation')),
                ('sub_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firs', to='location.SubDivision')),
            ],
            options={
                'verbose_name': 'FIR',
                'verbose_name_plural': 'FIRs',
                'ordering': ['-fir_no', 'phase'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='fir',
            unique_together={('sub_division', 'police_station', 'fir_no', 'phase')},
        ),
    ]
