# Generated by Django 2.1.5 on 2020-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='ssp_approved',
            field=models.BooleanField(default=False),
        ),
    ]
