# Generated by Django 2.1.5 on 2020-04-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0002_fir_ssp_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='accused_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='accused_status',
            field=models.CharField(blank=True, choices=[('arrested', 'Arrested'), ('not_arrested', 'Not Arrested'), ('po', 'PO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fir',
            name='appointed_io',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fir',
            name='court_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('reinvestigation', 'Reinvestigation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fir',
            name='put_in_court_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='received_from_court_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='received_in_court_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='reverted_by_court_date',
            field=models.DateField(blank=True),
        ),
    ]
