# Generated by Django 2.1.5 on 2020-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0003_auto_20200419_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='appointed_io',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='court_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('reinvestigation', 'Reinvestigation')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='put_in_court_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='received_from_court_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='received_in_court_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='reverted_by_court_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
