# Generated by Django 2.1.5 on 2020-04-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0004_auto_20200419_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='current_status',
            field=models.CharField(blank=True, choices=[('under_invertigation', 'Under Invertigation'), ('challan_filed', 'Challan Filed'), ('untraced', 'Untraced'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='limitation_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
