# Generated by Django 2.1.5 on 2020-04-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0005_auto_20200419_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='accused_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='accused_status',
            field=models.CharField(blank=True, choices=[('arrested', 'Arrested'), ('not_arrested', 'Not Arrested'), ('po', 'PO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='io_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
