# Generated by Django 3.0.7 on 2020-06-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0008_auto_20200609_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fir',
            options={'ordering': ['sub_division', 'police_station', '-fir_no', 'phase'], 'verbose_name': 'FIR', 'verbose_name_plural': 'FIRs'},
        ),
    ]
