# Generated by Django 3.0.7 on 2020-06-14 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0010_auto_20200612_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='date_created_on_system',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fir',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fir',
            name='date_created',
            field=models.DateField(),
        ),
    ]
