# Generated by Django 3.0.7 on 2020-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0011_auto_20200614_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
